language: node_js

node_js:
    - "node"

addons:
  apt:
    packages:
    - libgconf-2-4

notifications:
     email: false

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - npm ci
    - npm run cy:verify

install:
  - npm ci

script:
  - npm run ci
